"""Shared typed schemas for the Character Voice AI system.

Everything crossing a module boundary in this project is one of these types. Spec §23:
"use typed schemas" — this package is that instruction taken literally, so that a change
to the shape of a Voice Pack or a Speech Plan breaks loudly at import/validation time
rather than quietly at listening-test time.
"""

from __future__ import annotations

from .base import (
    LANGUAGE_ZH_CN,
    CVAIModel,
    Language,
    RelPath,
    SemVer,
    Slug,
    StyleTag,
    UnitFloat,
    parse_version,
    sha256_text,
    utcnow,
    validate_relative_path,
)
from .character import (
    CharacterProfile,
    DialogueExample,
    LLMSettings,
    MemorySettings,
    SpeakingHabits,
    VoiceBinding,
)
from .conversation import (
    ALLOWED_TRANSITIONS,
    ConversationState,
    InterruptReason,
    InterruptSignal,
    SessionConfig,
    StateTransition,
    Turn,
    can_transition,
)
from .evaluation import (
    AXIS_HIGHER_IS_BETTER,
    AXIS_PROMPTS,
    AggregateReport,
    AxisAggregate,
    BenchmarkCandidate,
    BenchmarkRun,
    BlindItem,
    BlindKey,
    BlindKeyEntry,
    BlindTestSet,
    CandidateAggregate,
    GenerationRecord,
    GroundTruthItem,
    HumanRating,
    ObjectiveMetrics,
    RatingAxis,
    SentenceCategory,
    TestSentence,
    TestSentenceSet,
    aggregate_axis,
)
from .llm import (
    LLMCapabilities,
    LLMMessage,
    LLMResponse,
    LLMStreamChunk,
    LLMUsage,
    Role,
)
from .speech_plan import CharacterSpeechPlan, SpeechChunk
from .stt import STTCapabilities, Transcript, TranscriptSegment
from .style import (
    CORE_STYLES,
    EMOTION_VECTOR_DIMS,
    SPEAKING_RATE_FACTOR,
    CoreStyle,
    EmotionVector,
    EndingStyle,
    PauseStyle,
    PitchProfile,
    SpeakingRate,
    StyleControls,
    StyleDefinition,
    VolumeStyle,
    resolve_style_chain,
)
from .tts import (
    AdaptationMode,
    ProviderCapabilities,
    ReferenceSelection,
    TTSHealth,
    TTSRequest,
    TTSResult,
    VoiceQualityHint,
)
from .voicepack import (
    CHECKPOINTS_DIR,
    CLEAN_DIR,
    DATASET_FILENAME,
    DATASETS_DIR,
    EVALUATION_DIR,
    MANIFEST_FILENAME,
    METADATA_DIR,
    PROCESSED_DIR,
    RAW_DIR,
    REFERENCES_DIR,
    REFERENCES_FILENAME,
    REJECTED_DIR,
    TRANSCRIPTS_DIR,
    VOICEPACK_DIRS,
    AudioProperties,
    CheckpointRef,
    DatasetEntry,
    DatasetManifest,
    DatasetSplit,
    ProcessingStage,
    ProcessingStep,
    ReferenceBank,
    ReferenceSample,
    RejectionReason,
    ReviewStatus,
    SourceInfo,
    TrainingSample,
    VoicePackManifest,
)

__all__ = [
    # base
    "CVAIModel",
    "LANGUAGE_ZH_CN",
    "Language",
    "RelPath",
    "SemVer",
    "Slug",
    "StyleTag",
    "UnitFloat",
    "parse_version",
    "sha256_text",
    "utcnow",
    "validate_relative_path",
    # style
    "CORE_STYLES",
    "EMOTION_VECTOR_DIMS",
    "SPEAKING_RATE_FACTOR",
    "CoreStyle",
    "EmotionVector",
    "EndingStyle",
    "PauseStyle",
    "PitchProfile",
    "SpeakingRate",
    "StyleControls",
    "StyleDefinition",
    "VolumeStyle",
    "resolve_style_chain",
    # character
    "CharacterProfile",
    "DialogueExample",
    "LLMSettings",
    "MemorySettings",
    "SpeakingHabits",
    "VoiceBinding",
    # voicepack
    "AudioProperties",
    "CHECKPOINTS_DIR",
    "CLEAN_DIR",
    "CheckpointRef",
    "DATASETS_DIR",
    "DATASET_FILENAME",
    "DatasetEntry",
    "DatasetManifest",
    "DatasetSplit",
    "EVALUATION_DIR",
    "MANIFEST_FILENAME",
    "METADATA_DIR",
    "PROCESSED_DIR",
    "ProcessingStage",
    "ProcessingStep",
    "RAW_DIR",
    "REFERENCES_DIR",
    "REFERENCES_FILENAME",
    "REJECTED_DIR",
    "ReferenceBank",
    "ReferenceSample",
    "RejectionReason",
    "ReviewStatus",
    "SourceInfo",
    "TRANSCRIPTS_DIR",
    "TrainingSample",
    "VOICEPACK_DIRS",
    "VoicePackManifest",
    # speech plan
    "CharacterSpeechPlan",
    "SpeechChunk",
    # tts
    "AdaptationMode",
    "ProviderCapabilities",
    "ReferenceSelection",
    "TTSHealth",
    "TTSRequest",
    "TTSResult",
    "VoiceQualityHint",
    # stt / llm
    "STTCapabilities",
    "Transcript",
    "TranscriptSegment",
    "LLMCapabilities",
    "LLMMessage",
    "LLMResponse",
    "LLMStreamChunk",
    "LLMUsage",
    "Role",
    # conversation
    "ALLOWED_TRANSITIONS",
    "ConversationState",
    "InterruptReason",
    "InterruptSignal",
    "SessionConfig",
    "StateTransition",
    "Turn",
    "can_transition",
    # evaluation
    "AXIS_HIGHER_IS_BETTER",
    "AXIS_PROMPTS",
    "AggregateReport",
    "AxisAggregate",
    "BenchmarkCandidate",
    "BenchmarkRun",
    "BlindItem",
    "BlindKey",
    "BlindKeyEntry",
    "BlindTestSet",
    "CandidateAggregate",
    "GenerationRecord",
    "GroundTruthItem",
    "HumanRating",
    "ObjectiveMetrics",
    "RatingAxis",
    "SentenceCategory",
    "TestSentence",
    "TestSentenceSet",
    "aggregate_axis",
]
