"""initial studio schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 19:51:03.777363
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('model_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('local', 'public_api', 'custom', name='connectionkind', native_enum=False, length=32), nullable=False),
    sa.Column('provider_type', sa.Enum('ollama', 'openai_compatible', name='providertype', native_enum=False, length=32), nullable=False),
    sa.Column('connection_mode', sa.Enum('backend_proxy', 'browser_local', 'local_bridge', name='connectionmode', native_enum=False, length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('draft', 'testing', 'connected', 'error', 'disabled', name='connectionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('generation_defaults', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_packs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('empty', 'uploading', 'processing', 'needs_review', 'ready', 'error', name='voicepackstatus', native_enum=False, length=32), nullable=False),
    sa.Column('storage_prefix', sa.String(length=200), nullable=False),
    sa.Column('rights_confirmed', sa.Boolean(), nullable=False),
    sa.Column('rights_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_duration_s', sa.Float(), nullable=False),
    sa.Column('usable_duration_s', sa.Float(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('rejected_files', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('voice_pack_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(length=300), nullable=False),
    sa.Column('source_file', sa.String(length=300), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('transcript_source', sa.String(length=64), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('emotion', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('human_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_pack_id'], ['voice_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_samples_voice_pack_id'), ['voice_pack_id'], unique=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('voice_pack_id', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('base_model', sa.String(length=64), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'validating', 'preparing', 'training', 'evaluating', 'completed', 'failed', 'cancel_requested', 'cancelled', name='trainingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('total_epochs', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('output_prefix', sa.String(length=200), nullable=True),
    sa.Column('log_key', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_hint', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('voice_model_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_pack_id'], ['voice_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_voice_pack_id'), ['voice_pack_id'], unique=False)

    op.create_table('voice_models',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('voice_pack_id', sa.String(length=32), nullable=True),
    sa.Column('training_job_id', sa.String(length=32), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('base_model', sa.String(length=64), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'invalid', 'archived', name='voicemodelstatus', native_enum=False, length=32), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reference_prefix', sa.String(length=200), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('evaluation_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_pack_id'], ['voice_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('avatar_key', sa.String(length=300), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('model_connection_id', sa.String(length=32), nullable=True),
    sa.Column('voice_model_id', sa.String(length=32), nullable=True),
    sa.Column('default_voice_style', sa.String(length=32), nullable=False),
    sa.Column('legacy_profile_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ready', 'incomplete', name='characterstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_connection_id'], ['model_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_model_id'], ['voice_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('voice_models')
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_voice_pack_id'))

    op.drop_table('training_jobs')
    with op.batch_alter_table('audio_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_samples_voice_pack_id'))

    op.drop_table('audio_samples')
    op.drop_table('voice_packs')
    op.drop_table('model_connections')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
