"""Voice pack scaffolding and validation.

The validator is the quality gate between Milestone 2 and Milestone 3: it answers "is
this pack good enough to start training on?" before a GPU-hour is spent. Most of its
checks map directly onto failure modes listed in spec §27 — a pack that only has one
reference clip per style, or whose styles have no audio at all, will produce exactly the
"identical intonation across all sentences" result the spec warns about, and it is much
cheaper to see that here than after a listening test.
"""

from __future__ import annotations

from enum import Enum
from pathlib import Path

from cvai_types import (
    CharacterProfile,
    CoreStyle,
    CVAIModel,
    DatasetManifest,
    DatasetSplit,
    ReferenceBank,
    VoicePackManifest,
)
from pydantic import Field

from .loaders import (
    load_voicepack_manifest,
    save_model_yaml,
    try_load_dataset_manifest,
    try_load_reference_bank,
)
from .paths import VoicePackPaths

#: Spec §19 asks for roughly 20-60 minutes of high-quality character speech.
MIN_RECOMMENDED_MINUTES = 20.0
MAX_USEFUL_MINUTES = 60.0
#: Below this, a style's reference clips cannot rotate and every line in that style will
#: be conditioned on the same audio.
MIN_REFERENCES_PER_STYLE = 2


class Severity(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class Issue(CVAIModel):
    severity: Severity
    code: str
    message: str
    context: dict[str, object] = Field(default_factory=dict)


class ValidationReport(CVAIModel):
    voicepack_id: str
    root: str
    issues: list[Issue] = Field(default_factory=list)
    stats: dict[str, object] = Field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not any(i.severity is Severity.ERROR for i in self.issues)

    def errors(self) -> list[Issue]:
        return [i for i in self.issues if i.severity is Severity.ERROR]

    def warnings(self) -> list[Issue]:
        return [i for i in self.issues if i.severity is Severity.WARNING]

    def render(self) -> str:
        lines = [f"Voice pack: {self.voicepack_id}  ({self.root})"]
        if self.stats:
            lines.append("")
            lines.append("Stats")
            for key, value in self.stats.items():
                lines.append(f"  {key}: {value}")
        symbol = {Severity.ERROR: "✗", Severity.WARNING: "!", Severity.INFO: "·"}
        if self.issues:
            lines.append("")
            lines.append("Findings")
            for issue in self.issues:
                lines.append(f"  {symbol[issue.severity]} [{issue.code}] {issue.message}")
        lines.append("")
        lines.append("PASS" if self.ok else "FAIL")
        return "\n".join(lines)


# --------------------------------------------------------------------------------------
# Scaffolding
# --------------------------------------------------------------------------------------

_README = """# Voice Pack: {display_name} (`{voicepack_id}`)

Generated by `cvai-voicepack init`. See `docs/VOICEPACK.md` for the full pipeline.

## Rules

1. **`raw/` is immutable.** Drop original audio here once and never write to it again.
   Every other directory can be deleted and regenerated from `raw/` plus the manifest.
2. **Optional cleaning stays off unless the audio needs it.** Source separation,
   de-reverb and denoising each remove part of the performance. Turn one on only after
   listening to what it does to this character, and record it in `processing_chain`.
3. **Reference clips need transcripts.** Several engines require the reference text, and
   a bank without it has to be rebuilt by hand.
4. **Keep at least two reference clips per style.** One clip per style means every line
   in that style is conditioned on the same audio.

## Layout

| Directory | Contents |
|---|---|
| `raw/` | untouched originals |
| `processed/` | intermediate stage outputs, regenerable |
| `clean/` | human-approved training audio |
| `rejected/` | filtered-out clips, kept with the reason |
| `transcripts/` | ASR output and human corrections |
| `metadata/` | `voicepack.yaml`, `dataset.json`, `references.json` |
| `references/` | Reference Bank, one subdirectory per style |
| `datasets/` | engine-specific exports |
| `checkpoints/` | character-specific fine-tuned models |
| `evaluation/` | benchmark runs and listening-test results |
"""


def scaffold_voicepack(
    paths: VoicePackPaths,
    manifest: VoicePackManifest,
    *,
    overwrite: bool = False,
) -> ValidationReport:
    """Create the directory tree and write the manifest."""
    if paths.manifest_file.exists() and not overwrite:
        raise FileExistsError(
            f"{paths.manifest_file} already exists; pass overwrite=True to replace it"
        )

    for directory in paths.all_dirs():
        directory.mkdir(parents=True, exist_ok=True)
        keep = directory / ".gitkeep"
        if not any(directory.iterdir()):
            keep.touch()

    # One subdirectory per declared style, so the bank's shape is obvious on disk even
    # before any clips exist (spec §10).
    for style in manifest.styles:
        style_dir = paths.references / style.name
        style_dir.mkdir(parents=True, exist_ok=True)
        if not any(style_dir.iterdir()):
            (style_dir / ".gitkeep").touch()

    save_model_yaml(manifest, paths.manifest_file)
    (paths.root / "README.md").write_text(
        _README.format(
            display_name=manifest.display_name, voicepack_id=manifest.voicepack_id
        ),
        encoding="utf-8",
    )
    return validate_voicepack(paths)


def default_styles() -> list[dict[str, str]]:
    """The core taxonomy (spec §9) as plain dicts, for building a starter manifest."""
    return [{"name": s.value, "core_style": s.value} for s in CoreStyle]


# --------------------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------------------


def validate_voicepack(
    paths: VoicePackPaths,
    *,
    profile: CharacterProfile | None = None,
    require_dataset: bool = False,
    require_references: bool = False,
) -> ValidationReport:
    """Check a pack's structure, manifest, reference bank and dataset."""
    issues: list[Issue] = []
    stats: dict[str, object] = {}

    def add(severity: Severity, code: str, message: str, **context: object) -> None:
        issues.append(Issue(severity=severity, code=code, message=message, context=context))

    if not paths.root.is_dir():
        return ValidationReport(
            voicepack_id=paths.root.name,
            root=str(paths.root),
            issues=[
                Issue(
                    severity=Severity.ERROR,
                    code="pack.missing",
                    message=f"voice pack directory does not exist: {paths.root}",
                )
            ],
        )

    for directory in paths.all_dirs():
        if not directory.is_dir():
            add(
                Severity.WARNING,
                "layout.missing_dir",
                f"expected directory is missing: {directory.name}/",
                directory=directory.name,
            )

    if not paths.manifest_file.is_file():
        return ValidationReport(
            voicepack_id=paths.root.name,
            root=str(paths.root),
            issues=[
                Issue(
                    severity=Severity.ERROR,
                    code="manifest.missing",
                    message=f"no manifest at {paths.manifest_file}",
                )
            ],
        )

    manifest = load_voicepack_manifest(paths)
    stats["voicepack_version"] = manifest.version
    stats["declared_styles"] = len(manifest.styles)

    if manifest.voicepack_id != paths.root.name:
        add(
            Severity.ERROR,
            "manifest.id_mismatch",
            f"manifest says voicepack_id={manifest.voicepack_id!r} "
            f"but the directory is {paths.root.name!r}",
        )

    if not manifest.styles:
        add(
            Severity.ERROR,
            "manifest.no_styles",
            "the pack declares no styles; the retriever and planner have nothing to target",
        )

    if not manifest.source.license_note:
        add(
            Severity.WARNING,
            "source.no_license_note",
            "no license_note recorded for the source audio",
        )

    _check_references(paths, manifest, issues, stats, require_references, add)
    _check_dataset(paths, manifest, issues, stats, require_dataset, add)

    if profile is not None:
        _check_profile_alignment(profile, manifest, paths, add)

    return ValidationReport(
        voicepack_id=manifest.voicepack_id,
        root=str(paths.root),
        issues=issues,
        stats=stats,
    )


def _check_references(
    paths: VoicePackPaths,
    manifest: VoicePackManifest,
    issues: list[Issue],
    stats: dict[str, object],
    required: bool,
    add,
) -> None:
    bank: ReferenceBank | None = try_load_reference_bank(paths)
    if bank is None:
        severity = Severity.ERROR if required else Severity.INFO
        add(
            severity,
            "references.missing",
            "no reference bank yet (metadata/references.json) — build it in Milestone 2",
        )
        return

    stats["reference_clips"] = len(bank.samples)
    coverage = bank.coverage()
    stats["reference_coverage"] = coverage

    if bank.voicepack_id != manifest.voicepack_id:
        add(
            Severity.ERROR,
            "references.id_mismatch",
            f"reference bank belongs to {bank.voicepack_id!r}, not {manifest.voicepack_id!r}",
        )
    if bank.voicepack_version != manifest.version:
        add(
            Severity.WARNING,
            "references.version_drift",
            f"reference bank was built for pack version {bank.voicepack_version}, "
            f"manifest is now {manifest.version}",
        )

    known_styles = {s.name for s in manifest.styles}
    for sample in bank.samples:
        if sample.style not in known_styles:
            add(
                Severity.ERROR,
                "references.unknown_style",
                f"reference {sample.reference_id!r} uses style {sample.style!r} "
                "which the manifest does not declare",
                reference_id=sample.reference_id,
            )
        audio = paths.root / sample.audio_path
        if not audio.is_file():
            add(
                Severity.ERROR,
                "references.missing_audio",
                f"reference {sample.reference_id!r} points at missing file {sample.audio_path}",
                reference_id=sample.reference_id,
            )
        if not sample.transcript.strip():
            add(
                Severity.ERROR,
                "references.no_transcript",
                f"reference {sample.reference_id!r} has no transcript; several engines "
                "require the reference text",
                reference_id=sample.reference_id,
            )

    for style in manifest.styles:
        count = coverage.get(style.name, 0)
        if count == 0:
            add(
                Severity.ERROR,
                "references.style_empty",
                f"style {style.name!r} is declared but has no reference clips; "
                "every line in that style will fall back to another style",
                style=style.name,
            )
        elif count < MIN_REFERENCES_PER_STYLE:
            add(
                Severity.WARNING,
                "references.style_thin",
                f"style {style.name!r} has only {count} reference clip; with one clip "
                "every line in this style is conditioned on the same audio",
                style=style.name,
            )


def _check_dataset(
    paths: VoicePackPaths,
    manifest: VoicePackManifest,
    issues: list[Issue],
    stats: dict[str, object],
    required: bool,
    add,
) -> None:
    dataset: DatasetManifest | None = try_load_dataset_manifest(paths)
    if dataset is None:
        severity = Severity.ERROR if required else Severity.INFO
        add(
            severity,
            "dataset.missing",
            "no dataset manifest yet (metadata/dataset.json) — build it in Milestone 2",
        )
        return

    usable = dataset.usable()
    minutes = dataset.total_seconds() / 60.0
    stats["dataset_samples_total"] = len(dataset.samples)
    stats["dataset_samples_usable"] = len(usable)
    stats["dataset_minutes_usable"] = round(minutes, 2)
    stats["dataset_minutes_by_style"] = dataset.minutes_by_style()

    if dataset.voicepack_id != manifest.voicepack_id:
        add(
            Severity.ERROR,
            "dataset.id_mismatch",
            f"dataset belongs to {dataset.voicepack_id!r}, not {manifest.voicepack_id!r}",
        )

    if minutes < MIN_RECOMMENDED_MINUTES:
        add(
            Severity.WARNING,
            "dataset.too_small",
            f"{minutes:.1f} min of approved audio; spec §19 targets "
            f"{MIN_RECOMMENDED_MINUTES:.0f}-{MAX_USEFUL_MINUTES:.0f} min",
            minutes=round(minutes, 2),
        )

    heldout = [e for e in dataset.splits if e.split is DatasetSplit.HELDOUT]
    if not heldout:
        add(
            Severity.WARNING,
            "dataset.no_heldout",
            "no held-out split; the benchmark needs real character lines that no engine "
            "was trained on, both as ground truth and as the listening-test anchor",
        )

    known_styles = {s.name for s in manifest.styles}
    unknown = {s.voice_style for s in usable} - known_styles
    if unknown:
        add(
            Severity.ERROR,
            "dataset.unknown_styles",
            f"approved samples use styles the manifest does not declare: {sorted(unknown)}",
        )

    missing_audio = [s.sample_id for s in usable if not (paths.root / s.audio_path).is_file()]
    if missing_audio:
        add(
            Severity.ERROR,
            "dataset.missing_audio",
            f"{len(missing_audio)} approved samples point at files that do not exist",
            sample_ids=missing_audio[:10],
        )

    unreviewed = [s for s in dataset.samples if s.review_status.value == "pending"]
    if unreviewed:
        add(
            Severity.WARNING,
            "dataset.unreviewed",
            f"{len(unreviewed)} samples have never been reviewed by a human",
        )

    destructive = [s.sample_id for s in usable if s.was_destructively_processed]
    if destructive:
        add(
            Severity.INFO,
            "dataset.destructive_processing",
            f"{len(destructive)} approved samples went through waveform-altering stages; "
            "keep a null-processing control set so the benchmark can tell whether that helped",
        )
    stats["destructively_processed"] = len(destructive)


def _check_profile_alignment(
    profile: CharacterProfile,
    manifest: VoicePackManifest,
    paths: VoicePackPaths,
    add,
) -> None:
    if profile.voice.voicepack_id != manifest.voicepack_id:
        add(
            Severity.ERROR,
            "profile.pack_mismatch",
            f"character {profile.character_id!r} points at voice pack "
            f"{profile.voice.voicepack_id!r}, not {manifest.voicepack_id!r}",
        )
    declared = {s.name for s in manifest.styles}
    missing = [s for s in profile.available_styles if s not in declared]
    if missing:
        add(
            Severity.ERROR,
            "profile.unsupported_styles",
            f"character declares styles its voice pack cannot perform: {missing}; "
            "the planner would request them and the retriever would silently fall back",
            styles=missing,
        )
    if profile.voice.default_reference_style not in declared:
        add(
            Severity.ERROR,
            "profile.bad_default_style",
            f"default_reference_style {profile.voice.default_reference_style!r} "
            "is not declared by the voice pack",
        )


def voicepack_summary(paths: VoicePackPaths) -> dict[str, object]:
    """Compact stats for reports and run manifests."""
    report = validate_voicepack(paths)
    return {"ok": report.ok, **report.stats}
